name: JVM Flags Testing with Coverage

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 17, 21]
        jvm_flag: [
        "-XX:+UseG1GC",
        "-XX:+UseStringDeduplication",
        "-Xms512m",
        "-XX:+UnlockDiagnosticVMOptions",
        "-XX:+UseAdaptiveSizePolicy"
        ]
      fail-fast: false

    name: Test on JDK ${{ matrix.java }} with JVM Flag ${{ matrix.jvm_flag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'

      - name: Log JVM Flag
        run: | 
          echo "Running with JVM flag: ${{ matrix.jvm_flag }}"

      - name: Maven Build with JVM Flag
        env:
          MAVEN_OPTS: ${{ matrix.jvm_flag }}
        run: mvn clean verify -B

      - name: Run Tests with Coverage
        env:
          MAVEN_OPTS: ${{ matrix.jvm_flag }}
        run: mvn test jacoco:report -B

      - name: Collect Jacoco Coverage
        if: success()
        run: |
          mkdir -p target/jacoco-reports/${{ matrix.java }}/${{ matrix.jvm_flag }}
          cp target/site/jacoco/jacoco.csv target/jacoco-reports/${{ matrix.java }}/${{ matrix.jvm_flag }}/jacoco.csv

      - name: Upload Coverage Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: target/jacoco-reports/